### ISSUE TITLE
dotgenerator.py appears broken

### ISSUE THREAD

**Issue by stiber** [UWB-Biocomputing/BrainGrid#252]
## *What kind* of issue is this?
* [X] Bug report
* [ ] Feature request
* [ ] Question not answered in documentation
* [ ] Cleanup needed

## *What* is affected by this?

Documentation generation.

## *How* do we replicate the issue/how would it work?

`python Tools/DiagramGenerator/dotGenerator.py ./Core/BGDriver.cpp diags`

## Expected behavior (i.e. solution or outline of what it would look like)

It should work and generate dot files. Instead, I get:
```
Optimizing directory search...
Hashing files....
File not found or some other IO error.
```

This error output is just a generic exception catch in main.

**Comment by shastrihm** [comment]
I was able to get the script to run and produce dot files after moving dotGenerator.py to the top level directory and passing it BGDriver.cpp instead of ./Core/BGDriver.cpp . Is this the intended behavior?

**Comment by shastrihm** [comment]
Changes made so far:
 

- Upgraded script from Python 2 to Python 3
- Script now generates PDFs automatically and places them in a folder called "dot_diagrams"
- Fixed a bug where is_inheritance never recognized inheritance relationships (the regex is fixed)
- Block overview graph has some visual improvements (master nodes are distinguishable)
- More flexible input: for example, the script now accepts both "./Core/BGDriver.cpp" and "BGDriver.cpp" as valid command line arguments
- Fixed a bug where some edges in the sys_overview graph vanish after being partly drawn. However, my solution to this was to set "concentrate=false" which might not be the best way to go. I'm guessing the source of this bug is the fact that some edges are invisible, but removing them causes graphviz to render a somewhat ugly graph.
- Updated part of the documentation to more accurately reflect the script's operation

Here are all the diagrams that the script produced:
[out_Inputs.dot.pdf](https://github.com/UWB-Biocomputing/BrainGrid/files/3244431/out_Inputs.dot.pdf)
[out_Layouts.dot.pdf](https://github.com/UWB-Biocomputing/BrainGrid/files/3244432/out_Layouts.dot.pdf)
[out_Matrix.dot.pdf](https://github.com/UWB-Biocomputing/BrainGrid/files/3244433/out_Matrix.dot.pdf)
[out_Neurons.dot.pdf](https://github.com/UWB-Biocomputing/BrainGrid/files/3244434/out_Neurons.dot.pdf)
[out_Recorders.dot.pdf](https://github.com/UWB-Biocomputing/BrainGrid/files/3244435/out_Recorders.dot.pdf)
[out_RNG.dot.pdf](https://github.com/UWB-Biocomputing/BrainGrid/files/3244436/out_RNG.dot.pdf)
[out_Synapses.dot.pdf](https://github.com/UWB-Biocomputing/BrainGrid/files/3244437/out_Synapses.dot.pdf)
[out_tinyxml.dot.pdf](https://github.com/UWB-Biocomputing/BrainGrid/files/3244438/out_tinyxml.dot.pdf)
[out_Utils.dot.pdf](https://github.com/UWB-Biocomputing/BrainGrid/files/3244439/out_Utils.dot.pdf)
[out_Connections.dot.pdf](https://github.com/UWB-Biocomputing/BrainGrid/files/3244440/out_Connections.dot.pdf)
[out_Core.dot.pdf](https://github.com/UWB-Biocomputing/BrainGrid/files/3244441/out_Core.dot.pdf)
[out_diags_block_overview.dot.pdf](https://github.com/UWB-Biocomputing/BrainGrid/files/3244442/out_diags_block_overview.dot.pdf)
[out_diags_sys_complete.dot.pdf](https://github.com/UWB-Biocomputing/BrainGrid/files/3244443/out_diags_sys_complete.dot.pdf)
[out_diags_sys_overview.dot.pdf](https://github.com/UWB-Biocomputing/BrainGrid/files/3244444/out_diags_sys_overview.dot.pdf)

**Comment by stiber** [comment]
Two things remaining:

1. Check if containment relation has diamond on the correct side of arcs.
2. Pull request.

**Comment by shastrihm** [comment]
I think you're right, the diamonds were on the wrong side of the arcs -- a quick change fixed that. Submitted a pull request.
