### ISSUE TITLE
Refactor initialization code to facilitate parameter validation

### ISSUE THREAD

**Issue by stiber** [UWB-Biocomputing/BrainGrid#64]
This is an extension to issue #16.

Right now, both the Model and SimulationInfo objects are created in BGdriver.cpp. However, the way they are created, and the order they are initialized from parsed parameter files, precludes some input validation. In particular:
- model is declared as a global pointer to a Model; simInfo is a local variable (a SimulationInfo).
- A default Model is created in main() and initialized by load_simulation_parameters(); the SimulationInfo object is created, initialized, and returned by makeSimulationInfo().
- model is initialized before simInfo is created and initialized.
- All of the parameters used to create simInfo are loaded by LoadSimParms() (which is called by load_simulation_parameters(), to make things confusing). These values are saved in global variables, then later used by makeSimulationInfo() to create and initialize simInfo.

This is confusing, and overly complex. Here are the suggested modifications:
1. Make simInfo a global pointer variable, like model.
2. Create a default SimulationInfo object, like is now done with the Model object.
3. Rename load_simulation_parameters() to something like LoadAllParameters().
4. Rename LoadSimParms() to something like LoadSimulationParameters().
5. Make all of the parameters that are now globals (but really only used temporarily, to hold values until simInfo is created) local variables in LoadSimulationParameters().
6. Have LoadSimulationParameters() initialize the (now global) simInfo. Do this _before_ calling Model:: readParameters(). This means that LoadSimulationParameters() will incorporate the code now in makeSimulationInfo().

This will mean that, when Model:: readParameters() executes, all of the simulation parameters will have loaded (including such things as the number of neurons). The second thing that needs to be done is to pass simInfo to Model:: readParameters(), so that it can use that information for input validation.

If it gets very cumbersome to pass simInfo to every Model method, a model object can hold a pointer to the simInfo object (we can create the simInfo object first, then pass it in when the model is constructed, for example).

**Comment by fumik** [comment]
Need to re-evaluate on the current code.

**Comment by stiber** [comment]
I'm adding @tchoi1131 and @destinyboyer to this issue, since their work will be renaming things and firming up some aspects of the XML file structure. This should also give them access to the thoughts in this thread, which I had forgotten existed!

**Comment by stiber** [comment]
@destinyboyer , @tchoi1131 , is this issue done? It seems like part of this was done (for example, some function renaming).

**Comment by tchoi1131** [comment]
I am a little bit confused by the suggested modification written on May 12, 2014 since the code base of BrainGrid has changed a lot. But, I guess this issue is about developing a mechanism in BrainGrid to validate input parameters after changing the parameter parsing code in this commit 89cab1eba6996ee3f4ed5318d72a75b415271ae8. 

If my guess is correct, I think we may create a global function in BGDriver.cpp to do validation and call it before the actual simulation starts. 

Or, we may create a method for validation in a new/old class. Then, pass the instances of all the parameter classes - neurons, synapses, connections and layout - to the validation method before doing the simulation.

The advantages are:
1. The validation would not be restricted to a parameter class. It could perform cross-validation between different parameter classes.
2. All the validation logic would be at the same place, which can ease the fixing, modifying and adding of  validation logic.

**Comment by stiber** [comment]
I'm going to call this closed. It triggered some cleanup, and a good part of it is superseded by issue #208
